### ISSUE TITLE
Windows restore is not working

### ISSUE THREAD

**Issue by drizt** [bvbfan/Minimize-All#7]
I press on Minimize-All applet icon. It minimize all my windows. I press again and not happens. It doesn't restore windows.

I use Fedora 27 with KDE Version 5.7.3

**Comment by bvbfan** [comment]
Recompile it and start it from terminal:
`plasmawindowed org.kde.plasma.minimizeall`
Can you provide log or something suspicious.
In Plasma 5.8 and 5.11 it works.

**Comment by drizt** [comment]
It was very strange my system behaviour. I reset KDE settings and problem gone.
